version: '3.3'

services:
  database:
    image: postgres
    container_name: postgres_1
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=outlaw
      - POSTGRES_DB=avito_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - cloud

  redis:
    image: redis-aof
    container_name: redis-1
    ports:
      - 6380:6380
    volumes:
      - redis_volume:/data
    networks:
      - cloud

  application:
    image: application-image
    container_name: application_1
    networks:
      - cloud
    ports:
      - 8081:8081
    depends_on: # запускается после постгреса и редиса
      - database
      - redis
    environment:
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=outlaw"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/avito_db"

volumes:
  postgres_volume:
    external: true
  redis_volume:
    external: true

networks:
  cloud:
    external: true

    # postgres - 172.18.0.2
    # redis - 172.18.0.3